packages:
  # all packages in subdirs of packages/ and components/
  - 'providers/*'
  - 'packages/*'
  - 'apps/*'
  - 'examples/*'
  - 'libs/*'
  - 'docs'
  # exclude packages that are inside test directories
  - '!**/test/**'
